field: e1d6a3d2-955b-42e4-bcf0-ae40fbffba4f # Content Post
fieldLayouts:
  07a0f9bc-5dd3-4478-9770-448cbdab0365:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2c25602-4953-49fc-a0ce-8fdac961d57b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a702e2e-6ce8-4bbc-9819-923d28f30c7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9a06d06-813d-4c92-bfab-1f6be8e4ed07 # Descriptions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c88b38d-1e3b-4257-a1f8-2d363f81daf2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 183a12e7-f4c8-48c4-8aac-c5778e74c813
        userCondition: null
fields:
  b2c25602-4953-49fc-a0ce-8fdac961d57b: # Title
    columnSuffix: hscgklex
    contentColumnType: text
    fieldGroup: null
    handle: titleText
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b9a06d06-813d-4c92-bfab-1f6be8e4ed07: # Descriptions
    columnSuffix: xgfjoona
    contentColumnType: text
    fieldGroup: null
    handle: descriptions
    instructions: null
    name: Descriptions
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: items
name: Items
sortOrder: 1
