fieldLayouts:
  6068c8ca-7bb1-481c-ba93-705ebd72bf7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5a7d382a-4423-426e-b35b-dc513e0f17a7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6ac94b75-691d-40c6-b678-2aa8dee3aa8d
        userCondition: null
handle: blogOverview
hasTitleField: false
name: 'Blog Overview'
section: da7f3bc1-4533-411c-a8db-8637e8ca2282 # Blog Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
