fieldLayouts:
  6068c8ca-7bb1-481c-ba93-705ebd72bf7d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5a7d382a-4423-426e-b35b-dc513e0f17a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 293cac4b-bd6e-4c92-98ca-eb719b885cda # Post Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aaa511c-10f9-46bb-96c7-89bbcca03d44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 907b94e8-b3cb-408b-a4ed-d497104b2d55 # Post Short Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c10cc151-7231-481a-9232-434d7cd2ac7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7acc60ca-d954-466f-9d9c-79ecb579ed62 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fabc35c-f281-47dc-9acc-9ef89cd58feb
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: be50f99b-b84e-45d6-99c6-9b79e5c52560 # Post Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14fe1c68-d5cb-4070-84fa-d20e8c15d6df
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6ac94b75-691d-40c6-b678-2aa8dee3aa8d
        userCondition: null
handle: blogOverview
hasTitleField: true
name: 'Blog Overview'
section: da7f3bc1-4533-411c-a8db-8637e8ca2282 # Blog Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
