fieldLayouts:
  e69b86d6-d5e9-4743-8fd5-c17007babeaf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7070c80-d28e-4411-b002-c66c303aaf4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39b136d0-11c1-49b1-b440-9a280976d4e4
        userCondition: null
handle: karrierePost
hasTitleField: true
name: 'Karriere Post'
section: b20b7ca8-6027-4f7f-a320-95ab24bc0b22 # Karriere Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
