fieldLayouts:
  fa25e6a9-c0b0-4e2d-8fe6-bc1592edbd22:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d134eae4-1925-468f-87b6-e57cd02312d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be50f99b-b84e-45d6-99c6-9b79e5c52560 # Post Image
            instructions: null
            label: Icon
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 531ae389-cc11-472d-aaa5-c1656f1bac84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c969cea5-b5b1-408f-a797-8806df0c5402 # Post Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15fbf079-0156-47eb-be55-f0507760be25
            userCondition: null
            warning: null
            width: 100
        name: Detail
        uid: 5300ab8c-1486-4c1e-a391-158153b30a9e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7acc60ca-d954-466f-9d9c-79ecb579ed62 # Button
            instructions: null
            label: 'Information Button'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca7d4cdb-76c5-4aec-9ab8-cd3bd51b5296
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 194a6035-bf5f-40ad-b10b-bc1c093841a9
            userCondition: null
          -
            elementCondition: null
            fieldUid: e1d6a3d2-955b-42e4-bcf0-ae40fbffba4f # Content Post
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f1869b4-647b-4bc3-bb39-1b240b495629
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0e0daa68-c0df-4aaa-8c33-19f070edf96c
        userCondition: null
handle: software
hasTitleField: true
name: Software
section: b2ea844f-e1dc-4538-a97d-a57a34bf1afe # Software Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
