fieldLayouts:
  3e74c7a0-4653-4b3a-8dd0-8570c00bad86:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6f5927b5-f231-4aee-9a3b-8e72b7031635
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 293cac4b-bd6e-4c92-98ca-eb719b885cda # Post Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7957a63-fb80-4302-b1d7-e8a975757148
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 170b0e9a-f69f-46c0-810f-b14d6378d6fe # Post Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83e2b33c-c3b8-4803-8cc4-e609804bb768
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4e1c9cb6-9342-462c-8be6-a5ff6da0e384
        userCondition: null
handle: softwareOverview
hasTitleField: false
name: 'Software Overview'
section: f5515f40-8f50-4d87-82f2-f2ea5e7ab68d # Software Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
