fieldLayouts:
  8b30de7d-f43a-4240-900e-89c2530695cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d58fa3d6-2039-436d-8e6a-eb1e7925814a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 293cac4b-bd6e-4c92-98ca-eb719b885cda # Post Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6e820ac-b48c-491e-85b7-8a182151b09e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 907b94e8-b3cb-408b-a4ed-d497104b2d55 # Post Short Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53968d38-0e63-48c7-8a1f-ceb58bb5d1ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7acc60ca-d954-466f-9d9c-79ecb579ed62 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e62aaf0f-a00c-452b-8cd7-737dc764c7ea
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: be50f99b-b84e-45d6-99c6-9b79e5c52560 # Post Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fca877a3-7157-4c38-8f84-e70bf0bd59d9
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 47860d54-e544-44b6-90ec-0674f2ec5274
        userCondition: null
handle: storiesOverview
hasTitleField: true
name: 'Stories Overview'
section: aa851b3e-e45e-4c23-8c3b-e540929c28fe # Stories Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
