fieldLayouts:
  f9dc7281-e99d-4a44-8bbc-8001fe76e655:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ac39602-164b-4856-94fa-e74733043237
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba2d3088-293a-42db-bb1f-9fb0ce0d9cf0
        userCondition: null
handle: storiesPost
hasTitleField: true
name: 'Stories Post'
section: b79a9ca5-e9d0-4e18-ad37-b38ee786a341 # Stories Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
