dateModified: 1657651281
elementSources:
  craft\elements\Entry:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: Channels
      type: heading
    -
      key: 'section:8032f6af-316d-418e-ab60-c0ce3c7f60f9' # Author
      type: native
    -
      key: 'section:f87ff7ae-50ba-4e06-a75e-899fdc075507' # Blog Post
      type: native
    -
      key: 'section:b20b7ca8-6027-4f7f-a320-95ab24bc0b22' # Karriere Post
      type: native
    -
      key: 'section:b2ea844f-e1dc-4538-a97d-a57a34bf1afe' # Software Post
      type: native
    -
      disabled: false
      key: 'section:b79a9ca5-e9d0-4e18-ad37-b38ee786a341' # Stories Post
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: admin@mail.com
  fromName: cloud4success
  transportType: craft\mail\transportadapters\Sendmail
fs:
  contentLocal:
    hasUrls: true
    name: 'Content Local'
    settings:
      path: $CONTENT_LOCAL_BASE_PATH
    type: craft\fs\Local
    url: $CONTENT_LOCAL_ROOT_URL
meta:
  __names__:
    0d358e98-2829-44be-a4f1-978b41d2f0aa: Software # Software
    1d7dc4a5-fcb3-477b-93d2-0adc9b88ccb6: 'Button Url' # Button Url
    2d382c82-c0eb-47c2-b9f6-05fd84e03045: 'Title Button' # Title Button
    3cfc0ef4-6ff2-433b-a452-2d40f9bc5988: 'Author Entry' # Author Entry
    3d8e84b0-a04d-41aa-b0b1-03a2b6171be0: 'Story Company' # Story Company
    3da196e2-18bf-4d1d-b323-c31fe0330c82: 'Stories Post' # Stories Post
    4c833b87-8963-49bf-b039-fb9029ebcfa6: Experience # Experience
    7acc60ca-d954-466f-9d9c-79ecb579ed62: Button # Button
    7b44a9da-6f5d-4f88-a792-23abfa8d885f: 'Blog Category' # Blog Category
    7d14fb5f-7ea2-4695-95f7-923c9bbd3fb8: Headline # Headline
    8bbb286a-ac71-4e2a-8a91-3dbff9e26b3d: 'Software Category' # Software Category
    9b168937-c11f-4a7e-9741-f9d6aa77c9d0: 'Job Detail' # Job Detail
    26f05fc1-ee8e-4be8-95cb-ee95fc0ba4ea: Button # Button
    39a78532-3890-491b-bacb-c9efe356997a: 'Title Button' # Title Button
    47ef9959-a528-4bd5-bd2d-c068e5248ae7: 'Karriere Post' # Karriere Post
    59f2d7a3-cddc-441d-b150-0e18e523e267: 'Stories Overview' # Stories Overview
    69d2ba66-2d6a-48f3-b8cc-0850d42e2c18: 'Blog Post' # Blog Post
    72e1ba88-7b1d-4682-804e-9e8fd8099292: Author # Author
    082ff081-aa3c-4188-afaf-1de984461e85: 'Company Category' # Company Category
    170b0e9a-f69f-46c0-810f-b14d6378d6fe: 'Post Rich Text' # Post Rich Text
    293cac4b-bd6e-4c92-98ca-eb719b885cda: 'Post Headline' # Post Headline
    604b0d19-51d0-48c3-b47a-2229a9ed23ac: Author # Author
    879b8fb2-8367-4ee2-846e-bd38b886d605: 'Post Company' # Post Company
    907b94e8-b3cb-408b-a4ed-d497104b2d55: 'Post Short Text' # Post Short Text
    913d328b-09f7-4108-8816-f81c35cb7d2a: 'Author Image' # Author Image
    987bd29f-6646-4a74-958b-01ebb601675b: 'Short Text' # Short Text
    2505b2b0-2821-445f-a8cc-a6c902395ae1: 'Url Button' # Url Button
    2855e71a-4ab6-45e5-b716-fe4cfc071f33: Location # Location
    7557a405-b2c2-48b3-8ab2-c99ea0fb0885: 'Karriere Overview' # Karriere Overview
    8032f6af-316d-418e-ab60-c0ce3c7f60f9: Author # Author
    9583ec6a-d404-475a-8632-f57bf1d4aa04: Duration # Duration
    16018a5d-e00b-488a-acca-11cd315f32dc: cloud4success # cloud4success
    33732ef7-8cf5-46e3-a85d-565e9c838e3d: cloud4success # cloud4success
    299609db-9eef-4aff-bcd8-5a92efda1dbb: Home # Home
    392575c9-9499-499c-b0cf-491dbb63a798: 'Blog Category' # Blog Category
    530023de-e527-4210-9215-b3e3099b4402: 'Author Name' # Author Name
    874730fc-5e59-488f-a579-29b8a3f524d0: 'Url Button' # Url Button
    5477467a-150b-4bea-ad59-e1f19719c73f: 'Blog Category' # Blog Category
    68486210-b568-4359-8c37-732c21e7518c: Job # Job
    a86f6dff-5be9-4f49-9232-841c9b5d8dda: Link # Link
    aa851b3e-e45e-4c23-8c3b-e540929c28fe: 'Stories Overview' # Stories Overview
    b2c25602-4953-49fc-a0ce-8fdac961d57b: Title # Title
    b2ea844f-e1dc-4538-a97d-a57a34bf1afe: 'Software Post' # Software Post
    b9a06d06-813d-4c92-bfab-1f6be8e4ed07: Descriptions # Descriptions
    b9db48ea-9351-4304-8538-27a6064de37e: Item # Item
    b20b7ca8-6027-4f7f-a320-95ab24bc0b22: 'Karriere Post' # Karriere Post
    b79a9ca5-e9d0-4e18-ad37-b38ee786a341: 'Stories Post' # Stories Post
    bc85457f-240f-437f-b96f-c024374ead45: Items # Items
    be50f99b-b84e-45d6-99c6-9b79e5c52560: 'Post Image' # Post Image
    c1d9166e-5308-4e91-9bf1-5618717bdcd8: 'Sofware Category' # Sofware Category
    c969cea5-b5b1-408f-a797-8806df0c5402: 'Post Banner' # Post Banner
    cae04bf8-01a2-4040-b9cc-6584b31aaaae: 'Content Assets' # Content Assets
    da7f3bc1-4533-411c-a8db-8637e8ca2282: 'Blog Overview' # Blog Overview
    dd2cab1f-d433-4267-bf6a-52fbb391b10f: Common # Common
    e0c0b0fa-c719-49dc-9c62-cfe77e3a05b2: Home # Home
    e1d6a3d2-955b-42e4-bcf0-ae40fbffba4f: 'Content Post' # Content Post
    e7a73574-4ac1-440a-9ecd-60810b7d4f02: Text # Text
    e9361ffe-b7e5-47e5-b505-06837d3a9487: 'Start Date' # Start Date
    e2192567-c6db-4e5b-99f3-be24ed73f518: 'Software Overview' # Software Overview
    ebe57e47-0c3e-420b-a5f2-f74dca7bb6ed: 'Blog Overview' # Blog Overview
    f0c8f2e7-dfeb-4a2b-a663-c1f3742952c4: 'Karriere Overview' # Karriere Overview
    f87ff7ae-50ba-4e06-a75e-899fdc075507: 'Blog Post' # Blog Post
    f5515f40-8f50-4d87-82f2-f2ea5e7ab68d: 'Software Overview' # Software Overview
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
system:
  edition: solo
  live: true
  name: cloud4success
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
