field: c969cea5-b5b1-408f-a797-8806df0c5402 # Post Banner
fieldLayouts:
  7dadae18-9197-4025-8595-dbb345ba800c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7d14fb5f-7ea2-4695-95f7-923c9bbd3fb8 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b9e0e32-f7f5-4650-b809-489a1e8b7b11
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 987bd29f-6646-4a74-958b-01ebb601675b # Short Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36fbca25-4dfa-4a1c-8f3a-707f451df117
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d7dc4a5-fcb3-477b-93d2-0adc9b88ccb6 # Button Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44b08bf3-ab86-4b39-be1e-f3aa0e793ae3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3eed3e8-4faa-4106-b3cd-bb3a5265a2cc
        userCondition: null
fields:
  1d7dc4a5-fcb3-477b-93d2-0adc9b88ccb6: # Button Url
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonUrl
    instructions: null
    name: 'Button Url'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7d14fb5f-7ea2-4695-95f7-923c9bbd3fb8: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  987bd29f-6646-4a74-958b-01ebb601675b: # Short Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: shortText
    instructions: null
    name: 'Short Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
