defaultPlacement: end
enableVersioning: true
handle: author
name: Author
propagationMethod: all
siteSettings:
  33732ef7-8cf5-46e3-a85d-565e9c838e3d: # cloud4success
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
