defaultPlacement: end
enableVersioning: true
handle: blogOverview
name: 'Blog Overview'
propagationMethod: all
siteSettings:
  33732ef7-8cf5-46e3-a85d-565e9c838e3d: # cloud4success
    enabledByDefault: true
    hasUrls: true
    template: _/blog/index
    uriFormat: blog
type: single
