defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  33732ef7-8cf5-46e3-a85d-565e9c838e3d: # cloud4success
    enabledByDefault: true
    hasUrls: true
    template: _/base/index
    uriFormat: __home__
type: single
