defaultPlacement: end
enableVersioning: true
handle: softwarePost
name: 'Software Post'
propagationMethod: all
siteSettings:
  33732ef7-8cf5-46e3-a85d-565e9c838e3d: # cloud4success
    enabledByDefault: true
    hasUrls: true
    template: _/software/entry
    uriFormat: 'm365/{slug}'
structure:
  maxLevels: 1
  uid: 19f2dbbe-ef61-4ec6-a763-a9681a4985f1
type: structure
