defaultPlacement: end
enableVersioning: true
handle: storiesPost
name: 'Stories Post'
propagationMethod: all
siteSettings:
  33732ef7-8cf5-46e3-a85d-565e9c838e3d: # cloud4success
    enabledByDefault: true
    hasUrls: true
    template: _/stories/entry
    uriFormat: 'success-stories/{slug}'
type: channel
